inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 3.0.0
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'docker/**/*'
    - '.vscode/**/*'
    - '.devcontainer/**/*'
    - '.git/**/*'
    - node_modules/**/*
    - db/schema.rb
    - bin/**/*
    - Rakefile
    - tmp/**/*